name: Jave CI/CD Pipeline with Docker

on:
 push:
  branches:
   - main
 pull_request:
  braches:
   - main


jobs:
  build:
    runs-on: ubuntu-latest
    

    steps:
      - name:checkout repository
        uses: actions/checkou@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache DOcker layers
        uses: actions/cache@v3
        with:
          path: /tml/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: |
          docker build -t your-image-name .

      - name: Run Docker container (Test phase)
        run: |
          docker run --name your-container-name -d your-image-name

      - name: Test the running Docker container
        run: |
          # Test your application running in Docker container (e.g., hit API endpoints, check logs)
          docker logs your-container-name

      - name: Clean up Docker container
        run: |
          docker stop your-container-name
          docker rm your-container-name

