name: Self-Hosted Runner Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted  # This tells GitHub Actions to use your self-hosted runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run tests
      run: |
        # Your build/test commands go here
        echo "Running tests on self-hosted runner"
