name: Self-Hosted Runner Test

on:
  push:
    branches:
      - main

jobs:
  test-runner:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print Runner Info
        run: |
          echo "This job is running on a self-hosted runner!"
          uname -a
          whoami
